---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-back-end-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-back-end-TabulateJarl8
  template:
    metadata:
      labels:
        app: birds-app-back-end-TabulateJarl8
    spec:
      containers:
        - image: 'ghcr.io/TabulateJarl8/birds-app-back-end:fab3538e685a513fda11b882f4c4b79c030a0abb'
          name: birds-back-front-end
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
